import Head from 'next/head'
import Image from 'next/image'
import io from 'socket.io-client'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const socket = io('http://localhost:3001', {
  
})

export default function Home() {
  const router = useRouter()
  const [message, setMessage] = useState('')
  const [chat, setChat] = useState([])

  useEffect(() => {
    const token = sessionStorage.getItem('token')
    if (!token) router.push('/login')
  }, [])

  useEffect(() => {
    socket.on('message', (message) => {
      setChat([...chat, message])
    })
    return () => {
      socket.disconnect()
    }
  }, [chat])

  const sendMessage = (e) => {
    e.preventDefault()
    socket.emit('message', message)
    setMessage('')
  }

  return (
    <>
      <Head>
        <title>Edutech App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>Chat en tiempo real</h1>
          <div>
            {chat.map((message, index) => (
              <div key={index}>{message}</div>
            ))}
          </div>
          <form onSubmit={sendMessage}>
            <input value={message} onChange={(e) => setMessage(e.target.value)} />
            <button type='submit'>Enviar</button>
          </form>
        </div>
      </main>
    </>
  )
}
